import {
  REACT_NATIVE_PUBLIC_API_URL,
  SECURE_STORE_ACCESS_TOKEN_DEVELOP,
  SECURE_STORE_ACCESS_TOKEN_PRODUCTION,
  SECURE_STORE_PREVIOUS_AUTH_PROVIDER,
} from "@env";

export const API_URL = REACT_NATIVE_PUBLIC_API_URL || "";

export const ACCESS_TOKEN_PRODUCTION = SECURE_STORE_ACCESS_TOKEN_PRODUCTION || "";
export const ACCESS_TOKEN_DEVELOP = SECURE_STORE_ACCESS_TOKEN_DEVELOP || "";
export const AUTH_PROVIDER_KEY = SECURE_STORE_PREVIOUS_AUTH_PROVIDER || "";
